---
- name: Remove Nginx and clean content
  hosts: all
  become: yes

  tasks:
    - name: Stop Nginx if running
      service:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Remove Nginx package
      apt:
        name: nginx
        state: absent
        purge: yes

    - name: Remove Nginx directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html
        - /etc/nginx
